export function About() {
    return (
        <>
        <h1>Termos de Uso</h1>


        <div>
<p>Estes termos de serviço (os “<strong>Termos</strong>”) estabelecem os termos e as condições em que a ADS Store oferece acesso para você usar e desfrutar de nossos jogos, aplicativos, sites e outros serviços (os “<strong>Serviços da ADS Store</strong>”). A ADS Store é uma empresa global de jogos eletrônicos sediada em Los Angeles, com escritórios e operações em todo o mundo. Quando dizemos “<strong>ADS Store</strong>,” estamos nos referindo à empresa da ADS Store responsável por fornecer os Serviços da ADS Store na sua região (veja <a href="#id.dhzr7hbtlg9b">Cláusula 19</a> abaixo), sendo que estes Termos constituem um acordo entre você e essa empresa.</p>

<p>Por favor, leia estes Termos com cuidado, prestando atenção especial aos seguintes itens:</p>
<ul><li><u><strong>Resolução de conflitos. Se você reside nos Estados Unidos, leia a cláusula de arbitragem vinculativa e a renúncia à ação coletiva na </strong></u><a href="#id.j1y4x7y5qxxs"><strong>Parte A da Cláusula 17</strong></a><u><strong>. Ela afeta a forma pela qual os conflitos entre nós são resolvidos.</strong></u></li>
<li><u><strong>Conteúdo virtual</strong></u>. Quando você clica para comprar, ganhar ou receber um Conteúdo Virtual, você obtém apenas uma licença para acessar o Conteúdo Virtual. Você não possui a propriedade sobre nenhum Conteúdo Virtual que desbloquear e não poderá transferi-lo para outra pessoa. O Conteúdo Virtual não tem valor monetário, geralmente é específico do jogo e você não pode resgatar Conteúdo Virtual por qualquer tipo de dinheiro do “mundo real”.</li>
<li><u><strong>Política de reembolso</strong></u>.Você perde o direito de mudar de ideia, cancelar o pedido e obter um reembolso se tiver acesso imediato ou baixar o seu conteúdo digital. Existem algumas exceções a essa regra, mas temos uma política rígida de reembolso. Saiba mais <a href="https://www.ADS Storegames.com/pt-br/global-refund-policy-BR" target="_blank">aqui</a>.</li>
<li><u><strong>Regras de usuário</strong></u>. Você concorda em seguir nossas Regras de Usuário (<a href="#id.ckruxq6urom7">Cláusula 7</a>). Essas regras regem o comportamento durante o jogo e também certas condutas fora do jogo durante o uso dos Serviços da ADS Store.</li></ul>
<h3>Atenção, pais!</h3>
<p>Fornecemos informações de classificação etária de jogos em nosso site. Também recomendamos que vocês supervisionem as atividades on-line de seu filho, analisem o conteúdo que ele está acessando e, se for o caso, monitorem suas interações sociais. Para mais informações sobre classificações etária de jogos e descrição de conteúdos, verifique seu sistema de classificação etária local.</p>
<header><h2>ÍNDICE</h2></header>
<ol><li><a href="#id.i3fdbmj4d8qk">SUA CONTA</a></li>
<li><a href="#id.oezr7wx22bhk">ENCERRAMENTO DA CONTA</a></li>
<li><a href="#id.svas12uxrnjp">LICENÇA LIMITADA</a></li>
<li><a href="#id.58z79wlsp309">PRODUTOS VIRTUAIS, MOEDA DO JOGO E COMPRAS</a></li>
<li><a href="#id.tzp5umycmyk">TAXAS E IMPOSTOS</a></li>
<li><a href="#id.29jn1srhli8v">POLÍTICA DE ENVIO DE IDEIAS NÃO SOLICITADAS</a></li>
<li><a href="#id.ckruxq6urom7">REGRAS DE USUÁRIO</a></li>
<li><a href="#id.a1s6fxqza1tl">CONTEÚDO GERADO PELO USUÁRIO</a></li>
<li><a href="#id.clx26zdoec9a">MONITORAMENTO</a><u> & ANTI-TRAPAÇA</u></li>
<li><a href="#id.513smaf9ncog">ATUALIZAÇÕES E MODIFICAÇÕES</a></li>
<li><a href="#id.1yetbuwergid">LINKS</a></li>
<li><a href="#id.rwa47sbs3d5m">AVISO E PROCEDIMENTO PARA RECLAMAÇÕES POR VIOLAÇÃO DE DIREITOS AUTORAIS</a></li>
<li><a href="#id.d0rk78307ojs">ISENÇÃO DE GARANTIA</a></li>
<li><a href="#id.favrfcy1e509">INDENIZAÇÃO</a></li>
<li><a href="#id.arlqp4qmfxpe">LIMITAÇÃO DE RESPONSABILIDADE</a></li>
<li><a href="#id.qrx9xp3diysn">LEI APLICÁVEL</a></li>
<li><a href="#id.7x2afytv2ia0">RESOLUÇÃO DE CONFLITOS</a></li>
<li><a href="#id.qhjqi6j9gbr2">TERMOS ADICIONAIS APLICÁVEIS AOS SERVIÇOS DA ADS Store</a></li>
<li><a href="#id.dhzr7hbtlg9b">PESSOAS JURÍDICAS DA ADS Store</a></li>
<li><a href="#id.x5svog5q1157">DISPOSIÇÕES GERAIS</a></li></ol>
<header><h2> SUA CONTA</h2></header>
<h4>1.1. <u>Eu posso criar uma conta e usar os Serviços da ADS Store?</u> (Você precisa ser um adulto ou ter permissão de seus pais ou responsável legal.)</h4>
<p>Você precisará de uma conta da ADS Store para acessar vários dos nossos serviços. Para criar uma conta e usar os Serviços da ADS Store, você precisa: (i) ser adulto; (ii) ser um menor emancipado; ou (iii) ter um consentimento válido dos pais ou responsável legal para ficar vinculado a estes Termos. Se você não é adulto nem é menor de idade emancipado, ou não entende esta Cláusula, fale com seus pais ou responsável legal e peça ajuda. Se você é um dos pais ou o responsável legal de um menor que criar uma conta conosco, você e o menor aceitam e concordam em obrigar-se de acordo com estes Termos. Você também é responsável por todo o uso da conta e pela conformidade com estes Termos por parte do menor, inclusive por todas as compras feitas na conta. Você não poderá criar ou usar uma conta nem utilizar qualquer um dos Serviços da ADS Store em nome de qualquer outra pessoa, física ou jurídica, nem para fins comerciais.</p>
<h4>1.2. <u>Como posso criar uma conta?</u> (Em nosso site ou usando autenticação social.)</h4>
<p>Você pode criar uma conta com credenciais de login exclusivas em nossos sites ou fazendo login nos Serviços da ADS Store com uma conta de rede social existente (se aplicável).</p>

<h4>1.3. <u>Preciso fornecer meu nome verdadeiro e outras coisas?</u> (Sim. Por favor, não tente inventar nomes engraçadinhos como “Com certeza não é o Blitzcrank” ou “Udyr nem pensar”.)</h4>
<p>Você sempre deve nos fornecer informações precisas e completas, inclusive seu nome verdadeiro.</p>
<h4>1.4. <u>Eu tenho várias contas de email diferentes. Faz diferença qual delas eu usar para registrar minha conta?</u> (Sim. Caso contrário, você poderá perder avisos importantes!)</h4>
<p>Enviamos avisos relacionados à conta, a questões jurídicas e serviços para o endereço de e-mail registrado em sua conta. Essas notificações podem ser realmente importantes (p. ex., uma notificação de que pretendemos encerrar sua conta por inatividade), portanto, você deve manter o endereço de e-mail associado à sua conta atualizado e (se solicitarmos) verificado. Se você criar uma conta fazendo login nos Serviços da ADS Store com uma conta de rede social, o e-mail da sua conta ADS Store será o endereço de e-mail associado a essa conta de rede social.</p>
<h4>1.5. <u>Posso compartilhar ou vender minha conta ou minhas credenciais de login?</u> (Não.)</h4>
<p>Quando você cria uma conta conosco, solicitamos que você selecione um nome de usuário e senha exclusivos (em conjunto, suas “<strong>Credenciais de Login</strong>”). Você concorda que:</p>
<ul><li>Você não pode compartilhar sua conta nem suas Credenciais de Login com ninguém.</li>
<li>Você não pode vender, transferir ou permitir que qualquer outra pessoa acesse sua conta ou suas Credenciais de Login, nem se oferecer para que terceiros pratiquem esses atos.</li>
<li>Você deve manter suas Credenciais de Login em segredo.</li></ul>

<p>Você deve nos notificar imediatamente se tomar conhecimento de qualquer violação de segurança, inclusive acesso não autorizado à conta ou perda, roubo ou uso não autorizado ou divulgação indevida de suas Credenciais de Login ou informações de pagamento, para que possamos tomar as medidas apropriadas. Você é responsável por todas as perdas (inclusive a perda ou o uso de Conteúdo Virtual) em sua conta, se você tiver compartilhado suas Credenciais de Login ou não conseguir manter sua conta ou suas Credenciais de Login em segurança.</p>
<header><h2>2. ENCERRAMENTO DA CONTA</h2></header>
<h4>2.1. <u>Como minha conta pode ser suspensa ou encerrada?</u> (Se você violar as regras, a Justiça Demaciana fará uma visita em sua conta!)</h4>
<p id="id.15m4mv4m5uc">2.1.1.<u><strong> Você</strong></u>. Você pode encerrar ou suspender sua conta a qualquer momento entrando em contato conosco por nossa página de suporte, no endereço <a href="https://support.ADS Storegames.com/hc/pt-br" target="_blank">https://support.ADS Storegames.com/hc/pt-br</a></p>
<p>2.1.2.<u><strong>Nós</strong></u>. Podemos encerrar ou suspender sua conta sem aviso prévio, se ficar determinado que:</p>
<ol><li>(a) você violou qualquer parte destes Termos (inclusive as Regras de Usuário);</li>
<li>(b) fazê-lo seria no melhor interesse de nossa comunidade ou dos Serviços da ADS Store ou é necessário para defender os direitos de terceiros;</li>
<li>(c) paramos de oferecer os Serviços da ADS Store em sua região (embora normalmente publicamos um aviso prévio em nosso site, aplicativo ou jogo, se planejamos deixar de oferecer um recurso principal de um jogo ou todos os Serviços da ADS Store em sua região);</li>
<li>você não pagou quaisquer taxas que nos devia (exceto nos casos de negligência grave ou dolo de nossa parte) ou se tivermos que reembolsar alguém devido ao uso não autorizado de um pagamento debitado de sua conta; ou</li>
<li>você tiver feito (ou se nós tivermos motivos razoáveis para suspeitar que você fez) uso não autorizado das informações de pagamento de outra pessoa.</li></ol>

<p>Podemos fazer essas determinações com a ajuda de sistemas automatizados e ferramentas de machine learning ou usando outros métodos que considerarmos adequados. Se você achar que cometemos um erro, entre em contato conosco com os detalhes e nós analisaremos seu caso, embora possamos suspender sua conta durante nossa análise. Você também pode contestar nossas decisões (veja a <a href="#id.7x2afytv2ia0">Cláusula 17</a>).</p>
<h4>2.2. <u>A ADS Store manterá minha conta para sempre, mesmo que eu pare de usá-la??</u> (Se você abandonar sua conta por um período muito longo, poderemos encerrá-la após enviarmos uma notificação para que você tenha oportunidade de reativá-la.)</h4>
<p>Se você não usar sua conta por um período prolongado, a ADS Store reserva o direito de tomar medidas em relação à sua conta, inclusive suspensão ou encerramento. Se pretendermos tomar medidas em relação à sua conta com base em período prolongado de inatividade, você será informado, primeiramente (p. ex., por e-mail para o endereço de e-mail registrado em sua conta), e terá ampla oportunidade de evitar tais medidas (p. ex., eliminação da sua conta).</p>
<h4>2.3. <u>O que acontece se a ADS Store encerrar minha conta?</u> (Você fica sem jogar e perderá o acesso a quaisquer compras, inclusive a Moeda do Jogo e os Produtos Virtuais.)</h4>
<p>Se sua conta for encerrada você não terá mais acesso à sua conta, inclusive aos dados associados ou ao Conteúdo Virtual (inclusive a Moeda do Jogo) (embora isso não limite nem afete nenhum direito que você eventualmente tiver segundo as leis de proteção de dados ou de defesa do consumidor). Quando encerramos sua conta por um motivo legítimo (por exemplo, se você violou estes Termos):</p>
<ul><li>você não terá direito a nenhum reembolso e nós não teremos nenhuma responsabilidade perante você; e</li>
<li>nós também nos reservamos o direito de cancelar quaisquer outras contas que você possa ter criado, bem como o seu acesso a quaisquer outros Serviços da ADS Store (também sem quaisquer ressarcimentos ou responsabilidade para com você).</li></ul>

<p>Você entende e concorda que ao utilizar os Serviços da ADS Store haverá o risco de sua conta ser encerrada ou suspensa de acordo com estes Termos. Sempre que você usar os Serviços da ADS Store, tenha esse risco em mente e sempre se comporte de maneira adequada.</p>
<header><h2>3. LICENÇA LIMITADA</h2></header>
<h4>3.1. <u>O que posso fazer com os Serviços da ADS Store?</u> (Você pode usufruir dos Serviços da ADS Store para seu próprio uso pessoal, não comercial.)</h4>
<p>Concedemos a você uma licença limitada, não exclusiva, intransferível e revogável para usar e desfrutar dos Serviços da ADS Store (e qualquer Conteúdo Virtual) apenas para fins individuais, não comerciais, de entretenimento e expressamente condicionados à sua observância dos termos deste Contrato. Se encerrarmos sua conta, qualquer licença concedida a você sobre os Serviços da ADS Store, assim como o Conteúdo Virtual, estará cancelada automaticamente. Salvo se autorizado pela ADS Store expressamente em contrário, em contrato escrito e assinado, você não poderá vender, copiar, trocar, emprestar, fazer engenharia reversa, descompilar, derivar código-fonte, traduzir, arrendar, dar em garantia, transferir, publicar, ceder ou de outra forma distribuir qualquer um dos Serviços da ADS Store ou qualquer propriedade intelectual da ADS Store, inclusive qualquer código de computador nosso ou o Conteúdo Virtual.</p>
<h4>3.2. <u>Posso fazer coisas com a propriedade intelectual da ADS Store</u> (Reservamos todos os direitos à nossa PI, mas permitimos alguns usos pessoais e não comerciais, como fan art.)</h4>
<p>Nós (e nossos licenciantes) detemos e reservamos todos os direitos, titularidade e participações sobre os Serviços da ADS Store, assim como de todos os dados e conteúdos publicados, gerados, fornecidos ou disponibilizados de outra forma nos Serviços da ADS Store, ou por meio deles, inclusive contas de usuário, código de computador, títulos, objetos, artefatos, personagens, nomes de personagens, logs de chats, gravações e transmissões de jogos, locais, nomes de locais, histórias, diálogos, frases de efeito, arte, gráficos, desenhos estruturais ou de paisagens, animações, sons, composições e gravações musicais, produtos virtuais, moeda do jogo, efeitos audiovisuais, imagem e semelhança gráfica das personagens, métodos de operação e jogabilidade (coletivamente, “Conteúdo do Jogo”). Para não deixar dúvida, o Conteúdo do Jogo inclui Conteúdo Virtual. Você não pode criar nenhum trabalho/obra intelectual de autoria própria com base no Conteúdo do Jogo ou nos Serviços da ADS Store, exceto conforme expressamente permitido por nós. Para obter mais informações sobre o uso por parte de fãs permitido atualmente, leia nossa política <a href="https://www.ADS Storegames.com/pt-br/juridico" target="_blank">Jibber Jabber Jurídico</a> (mas lembre-se de que podemos mudar isso periodicamente -- e para certas regiões onde temos parceria com terceiros, os termos de serviço do parceiro podem substituir as disposições da política).</p>

<p>Você também concorda que, a menos que lhe concedamos uma licença, em um contrato escrito assinado, você nunca poderá usar nenhuma de nossas marcas, marcas de serviço, nomes comerciais, logotipos, nomes de domínio, slogans de marca ou trade dress. Qualquer reprodução, redistribuição ou modificação dos Serviços da ADS Store, ou o uso dos Serviços da ADS Store que não esteja de acordo com este Contrato, é expressamente proibido e poderá resultar em severas penalidades civis e/ou criminais.</p>
<header><h2>4. PRODUTOS VIRTUAIS, MOEDA DO JOGO E COMPRAS</h2></header>
<h4>4.1. <u>O que é Conteúdo Virtual?</u> (O Conteúdo Virtual inclui itens como moeda do jogo e produtos virtuais, como campeões, skins, emotes, acessórios etc)</h4>
<p>Ao usar os Serviços da ADS Store, podemos oferecer a você oportunidades de adquirir uma licença limitada para acessar bens virtuais, como campeões, skins, emotes etc., (“Produtos Virtuais”) e moeda do jogo (“Moeda do Jogo”), associado à sua conta (em conjunto, denominados “Conteúdo Virtual”).</p>
<p>A Moeda do Jogo somente poderá ser usada para o jogo específico para o qual foi comprada, a menos que seja informado o contrário no momento da compra.</p>
<h4>4.2. Como consigo uma "licença" para acessar o Conteúdo Virtual? (Compre, ganhe ou receba.)</h4>
<p>Podemos oferecer a você várias oportunidades para adquirir uma licença limitada para acessar a Moeda do Jogo ou o Conteúdo Virtual, inclusive:</p>
<ol><li>comprá-la (p. ex., com cartão de crédito);</li>
<li>ganhá-la (p. ex., cumprindo missões ou tarefas de jogo); ou</li>
<li>recebê-la (p. ex., de outro jogador como presente ou usar a funcionalidade de criação como Hextech®).</li></ol>
<h4>4.3. <u>Eu “possuo” o Conteúdo Virtual que desbloqueio?</u> (Não. O que você "desbloqueia" não é o produto virtual em si, mas uma licença limitada intransferível para acessá-lo.)</h4>
<p>Você não possui nenhuma propriedade ou direito sobre qualquer Conteúdo Virtual que desbloqueia, independentemente de como adquiriu acesso a ele. O Conteúdo Virtual não tem valor monetário. Você não pode transferir (a menos que permitamos isso na funcionalidade dos Serviços da ADS Store) nem resgatar Conteúdo Virtual por qualquer tipo de dinheiro do “mundo real”. Você não pode obter nenhum reembolso pela compra de uma licença para acessar o Conteúdo Virtual, exceto conforme expressamente permitido por nós. Você pode consultar nossa política atual de reembolso de conteúdo <a href="https://www.ADS Storegames.com/pt-br/global-refund-policy-BR" target="_blank">aqui</a>.</p>
<h4>4.4. <u>Mais uma vez: não possuo meu Conteúdo Virtual?</u> (Não!", gritaram todos os advogados.)</h4>
<p>Quando você obtém nosso Conteúdo Virtual, o que estamos realmente oferecendo a você é uma licença e um direito pessoal, não exclusivos, intransferíveis, não sublicenciáveis, revogáveis, limitados, para usar esse Conteúdo Virtual apenas em relação ao uso que você fizer dos Serviços da ADS Store em questão.</p>

<p><u><strong>Não obstante qualquer disposição em contrário neste documento, você reconhece e concorda que não terá nenhum direito de propriedade ou outro tipo de direito sobre sua conta, e que todos os direitos de sua conta são e sempre serão de propriedade da ADS Store e reverterão em benefício desta. Você também reconhece e concorda que você não tem nenhuma titularidade, direito de propriedade ou outro tipo de direito exclusivo sobre qualquer Conteúdo Virtual, independentemente de qualquer contraprestação oferecida ou paga em troca. Além disso, exceto nos casos de má conduta dolosa ou negligência grave, ou na medida em que estes Termos dispuserem o contrário, a ADS Store não será responsável de maneira alguma pela destruição, exclusão, modificação, comprometimento, hacking ou qualquer outro dano ou perda de qualquer tipo causado ao Conteúdo Virtual, inclusive a exclusão do Conteúdo Virtual após o encerramento ou vencimento da sua conta ou nossas alterações razoáveis aos Serviços da ADS Store.</strong></u></p>
<h4>4.5. <u>Meu Conteúdo Virtual estará sempre disponível</u> (Não necessariamente, não.)</h4>
<p>Em um esforço para melhorar constantemente os Serviços da ADS Store, desenvolver nossos jogos e manter os Serviços da ADS Store seguros, divertidos e protegidos, temos o direito de excluir, alterar, mover, remover, re-empacotar, re-precificar ou transferir todo e qualquer Conteúdo do Jogo, inclusive o Conteúdo Virtual, no todo ou em parte, a qualquer momento, com ou sem aviso prévio e sem qualquer responsabilidade perante você. Por exemplo, seus Produtos Virtuais podem (e provavelmente continuarão a) evoluir ao longo do tempo a fim de melhorar os Serviços da ADS Store ou por razões regulamentares ou legais. Se decidirmos retirar completamente certos Produtos Virtuais que você tenha comprado recentemente, providenciaremos uma substituição. Não excluiremos sua Moeda do Jogo sem aviso prévio (através de postagens em nosso site, aplicativo ou jogo), a menos que sua conta seja encerrada por um motivo legítimo ou por você de acordo com <a href="#id.15m4mv4m5uc">Cláusula 2.1.1</a>. Às vezes, podemos alterar o poder de compra da Moeda do Jogo (por exemplo, podemos aumentar o número de Moedas do Jogo necessárias para comprar Produtos Virtuais, como skins). Normalmente, fazemos isso apenas em etapas progressivas, mas você será avisado (por meio de postagens em nosso site, aplicativo ou jogo) se pretendermos fazer alterações que afetem significativamente sua Moeda do Jogo de maneira negativa. Não fornecemos nem garantimos, e negamos expressamente, qualquer valor, em dinheiro ou de outra forma, atribuído a quaisquer dados residentes nos servidores que operamos ou controlamos, inclusive qualquer Conteúdo do Jogo ou Conteúdo Virtual atribuído à sua conta. Se permitirmos a venda ou transferência do seu direito de acessar determinado Conteúdo do Jogo ou Conteúdo Virtual, ele só poderá ser realizado através de serviços aprovados ou fornecidos por nós, se houver.</p>
<header><h2>5. TAXAS E IMPOSTOS</h2></header>
<h4>5.1. <u>Tudo nos Serviços da ADS Store é gratuito?</u> (Não.)</h4>
<p>Alguns aspectos dos Serviços da ADS Store podem exigir que você pague uma taxa, e você concorda em fornecer informações de pagamento exatas e completas para nós ou para um terceiro administrador de pagamentos usado por nós. Você também concorda em pagar todas as taxas e os impostos aplicáveis incidentes em sua conta. Podemos ajustar os preços de qualquer parte dos Serviços da ADS Store a qualquer momento. Isso pode afetar o poder de compra da sua Moeda do Jogo, embora normalmente o façamos apenas em etapas graduais. Todas as taxas e cobranças são devidas de acordo com as condições de pagamento em vigor no momento em que a taxa ou a cobrança se torna exigível. Ocasionalmente, podemos modificar, alterar ou complementar nossas taxas e métodos de cobrança, sendo que essas alterações entrarão em vigor imediatamente após a publicação nestes Termos ou em qualquer outro lugar em nossos sites, aplicativos ou jogos. Exceto nos casos de negligência grave ou conduta dolosa, se você não pagar as taxas que nos deve ou se tivermos de reembolsar alguém devido ao uso não autorizado de um pagamento feito em sua conta, poderemos suspender ou encerrar sua conta. Consulte a <a href="#id.oezr7wx22bhk">Cláusula 2</a> (Encerramento da Conta) para obter mais informações.</p>

<p><u><strong>Sujeito à lei aplicável, quaisquer taxas aplicáveis e outras cobranças por serviços baseados em taxas (inclusive a Moeda do Jogo) são pagas antecipadamente e não são reembolsáveis, no todo ou em parte, exceto conforme expressamente previsto nestes Termos. Salvo em casos de negligência grave ou dolo por parte da ADS Store, ou na medida em estes Termos disponham o contrário, você é totalmente responsável por todas as despesas debitadas em sua conta, inclusive quaisquer despesas não autorizadas.</strong></u></p>
<h4>5.2. <u>Quais são as minhas responsabilidades relacionadas à Moeda do Jogo?</u> (Pagar os impostos incidentes; verificar se todas as transações conosco estão corretas, etc.)</h4>
<p>Você é o único responsável pelo pagamento de quaisquer impostos incidentes relacionados à aquisição, ao uso ou ao acesso à Moeda do Jogo. A Moeda do Jogo pode ser vendida ou emitida por nós em pacotes e o preço pode variar dependendo do valor que você compra e de onde está comprando. Conforme acharmos necessário, a nosso critério (ou conforme prescrito por lei), poderemos limitar o valor total da Moeda do Jogo que pode ser comprado para qualquer jogo ou o total de Moeda de Jogo que pode ser mantido em sua conta. Além disso, o preço e a disponibilidade da Moeda do Jogo e dos Produtos Virtuais estão sujeitos a alterações. Poderemos restringir a Moeda do Jogo que você poderá comprar e/ou usar com base em sua localização, pois temos abordagens diferentes em locais diferentes.</p>
<p>Você deve verificar se a quantidade adequada de Moeda do Jogo foi adicionada ou deduzida da sua conta durante qualquer transação. Notifique-nos imediatamente se você acreditar que um erro foi cometido em relação ao seu saldo de Moeda do Jogo. Investigaremos sua reclamação e, ao fazer isso, solicitaremos mais informações para verificação.</p>
<header><h2>6. POLÍTICA DE ENVIO DE IDEIAS NÃO SOLICITADAS</h2></header>
<h4>6.1. <u>Posso enviar ideias para melhorar o Jogo à ADS Store?</u> (Por favor, não. Se você fizer assim mesmo, teremos o direito absoluto de usá-las para sempre.)</h4>
<p>Valorizamos seu feedback sobre os Serviços da ADS Store, mas não envie ideias, sugestões ou materiais criativos para nós (em conjunto, denominadas “Ideias Não Solicitadas”). Poderemos usar livremente qualquer uma dessas Ideias Não Solicitadas que você fornecer. Esta política tem como objetivo evitar possíveis mal-entendidos ou conflitos, caso os Serviços da ADS Store eventualmente pareçam semelhantes às Ideias Não Solicitadas enviadas pelas pessoas.</p>

<p>Apesar de você não ter direitos legais sobre as Ideias Não Solicitadas que insistir em nos enviar, se o fizer, teremos permissão para usar todas ou algumas de suas Ideias Não Solicitadas por qualquer motivo que escolhermos e sem nenhum pagamento a você.</p>

<p>Em termos jurídicos, isso significa que, se você nos enviar Ideias Não Solicitadas, estará nos concedendo um direito e uma licença mundial, perpétua, irrevogável, sublicenciável, transferível, sujeita a cessão, não-exclusiva, e isenta de royalties, para utilizar, reproduzir, distribuir, adaptar, modificar, traduzir, criar obras derivadas, executar publicamente, exibir publicamente, digitalmente realizar, fazer, mandar fazer, vender, pôr à venda, e importar as suas Ideias Não Solicitadas, inclusive todos os direitos autorais, marcas, segredos comerciais, patentes, projetos, direitos de propriedade industrial, bem como todos os outros direitos de propriedade intelectual e proprietários relacionados, em qualquer mídia atualmente conhecida ou a ser desenvolvida no futuro, para qualquer finalidade, comercial ou outra, inclusive dando as Ideias Não Solicitadas a outras pessoas, sem qualquer indenização para você. Na medida do necessário, você se compromete a assinar e entregar todos e quaisquer documentos e praticar todos e quaisquer atos necessários ou desejáveis a fim de garantir que os direitos de uso das Ideias Não Solicitadas concedidos a nós, conforme especificado acima, sejam válidos, eficazes, e exigíveis, assim renunciando a qualquer reclamação que exija - e prometendo nunca reclamar - o cumprimento de tais direitos na medida máxima do permitido pelas leis de sua região.</p>
<header><h2>7. REGRAS DE USUÁRIO</h2></header>
<h4>7.1. <u>Posso ‘trollar’, insultar, ameaçar ou assediar pessoas enquanto estiver usando os Serviços da ADS Store?</u> (Não. Se você fizer isso, podemos tomar medidas como cancelar sua conta.)</h4>
<p>Ao usar os Serviços da ADS Store, você deve cumprir todas as leis, regras e regulamentos da região em que reside. Você também deve cumprir as políticas de uso e comportamento aceitáveis que publicamos periodicamente em nossos sites, aplicativos e jogos e as regras de comportamento listadas abaixo (em conjunto, denominadas “<strong>Regras de Usuário</strong>”). As Regras de Usuário publicadas em nossos sites, aplicativos e jogos ou definidas nesta Cláusula não são exaustivas, e a ADS Store se reserva o direito de modificá-las, bem como tomar medidas disciplinares apropriadas, inclusive banimentos temporários, suspensão, ou encerramento e exclusão da conta a fim de proteger a integridade e o espírito dos Serviços da ADS Store, independentemente de um comportamento específico estar listado nas Regras de Usuário como inadequado.</p>
<p>A seguir, exemplos de comportamento que justificam medidas disciplinares:</p>
<ol><li>Fazer-se passar por qualquer pessoa, empresa ou entidade, até mesmo um funcionário da ADS Store, ou se comunicar de qualquer maneira que pareça que a comunicação se origina da ADS Store;</li>
<li>Postar publicamente informações de identificação sobre você, funcionários da ADS Store ou outros jogadores;</li>
<li>Assediar, perseguir ou ameaçar outros jogadores ou funcionários da ADS Store;</li>
<li>Remover, alterar ou ocultar qualquer aviso de direitos autorais, direitos marcarios, patente ou outro aviso de direitos proprietários da ADS Store contidos nos Serviços da ADS Store. Você também não pode transmitir conteúdo que viole ou infrinja os direitos de terceiros, inclusive patente, marca, segredo comercial, direitos autorais, direitos de imagem, direitos pessoais ou outros direitos;</li>
<li>Transmitir ou comunicar qualquer conteúdo que acreditamos razoavelmente ser ofensivo para os jogadores, inclusive linguagem que seja ilegal, prejudicial, ameaçadora, abusiva, assediadora, difamatória, vulgar, obscena, sexualmente explícita ou racialmente, eticamente ou de outra forma condenável;</li>
<li>Transmitir ou facilitar a transmissão de qualquer conteúdo que contenha vírus, dados corrompidos, cavalo de Troia, <em>bot keystroke logger, worm, time bomb, cancelbot </em>ou outros programas de computador ou códigos que se destinem a danificar e/ou realmente danifiquem, interfiram de maneira prejudicial, e clandestinamente interceptem ou extraiam, anulem ou roubem qualquer sistema, dados ou informações pessoais;</li>
<li>Evitar, desviar, remover, desativar, prejudicar, decodificar ou de outra forma contornar qualquer medida tecnológica implementada pela ADS Store ou por qualquer terceiro a fim de proteger ou controlar o acesso aos Serviços da ADS Store ou qualquer parte deles;</li>
<li>Enviar spam, seja para fins pessoais ou comerciais, interrompendo o fluxo da conversa com postagens repetidas;</li>
<li>Participar de qualquer ação que acreditemos razoavelmente que possa ser enganar ou esteja enganando qualquer outro jogador, inclusive por meio de golpe ou engenharia social ;;</li>
<li>Usar programas de terceiros não autorizados, inclusive <em>mods, hacks, cheats, scripts, bots, trainers</em> e programas de automação que interajam com os Serviços da ADS Store de qualquer forma, para qualquer finalidade, inclusive quaisquer programas de terceiros não autorizados que interceptem, emulem ou redirecionem qualquer comunicação relativa aos Serviços da ADS Store e quaisquer programas de terceiros não autorizados que coletem informações sobre os Serviços da ADS Store lendo áreas de memória usadas pelos Serviços da ADS Store para armazenar informações;</li>
<li>Acessar ou tentar acessar áreas dos Serviços da ADS Store que não tenham sido disponibilizadas ao público;</li>
<li>Selecionar uma conta ou nome de usuário que seja falsamente indicativo de uma associação com a ADS Store, contenha informações de identificação pessoal, ou que sejam ofensivas, difamatórias, vulgares, obscenas, sexualmente explícitas, racial ou eticamente censuráveis ou de qualquer outra forma condenáveis. Você não poderá usar erros ortográficos ou ortografia alternativa para contornar essa restrição nas escolhas de nomes, tais como nomes de usuário. A ADS Store poderá modificar qualquer nome que, a critério exclusivo da ADS Store, viole esta cláusula, sem notificar você, podendo tomar outras medidas disciplinares, inclusive o encerramento da conta em razão de violações recorrentes;</li>
<li>Não participar, fazer logout ou sair durante uma partida ativa. A ADS Store pode rastrear esses dados ao longo do tempo e banir temporariamente u m jogador quando ficar determinado que este saiu no meio do jogo muitas vezes. A duração do banimento temporário aumentará com o tempo se uma conta em particular continuar a sair de uma partida ativa;</li>
<li>Jogar na conta de outra pessoa ou se envolver em atividades destinadas a "melhorar" o status ou a classificação de uma conta;</li>
<li>Induzir ou incentivar outras pessoas a violarem as Regras de Usuário ou estes Termos; ou</li>
<li>Usar os Serviços da ADS Store para qualquer finalidade comercial, sem o nosso consentimento expresso por escrito ou após solicitarmos que você deixe de usar os Serviços da ADS Store.</li></ol>
<header><h2>8. CONTEÚDO GERADO PELO USUÁRIO</h2></header>
<h4>8.1. <u>Sou responsável pelo conteúdo que eu publicar nos ADS Store Services?</u> (Sim, e podemos usar o que você postar.)</h4>
<p>Além das Ideias Não Solicitadas (abordadas separadamente, na <a href="#id.29jn1srhli8v">Cláusula 6</a>, acima), você também é responsável por quaisquer outras comunicações, nomes de usuário, imagens, sons ou outros materiais e informações que você criar, enviar, usar ou transmitir com ou através dos Serviços da ADS Store(“<strong>Seu Conteúdo</strong>”).</p>
<p>Você deve fazer upload ou transmitir Seu Conteúdo apenas se concordar que:</p>
<ol><li>Você nos concede, desde o momento do upload ou da transmissão de Seu Conteúdo, um direito e uma licença mundial, perpétua, irrevogável, sublicenciável, não-exclusiva, sem direito a royalties, bem como uma licença para utilizar, reproduzir, distribuir, adaptar, modificar, traduzir, criar obras derivadas, executar publicamente, exibir publicamente, executar digitalmente, fazer, mandar fazer, e importar Seu Conteúdo, inclusive todos os direitos autorais, marcas, segredos comerciais, patentes, direitos industriais e todos os outros direitos de propriedade intelectual e direitos proprietários a eles relacionados, com a finalidade de fornecer os Serviços da ADS Store sem qualquer indenização para você;</li>
<li>Você renuncia a quaisquer direitos morais que possa ter sobre Seu Conteúdo com relação ao uso que fizermos de Seu Conteúdo, na extensão máxima permitida pelas leis de sua região. Se as leis locais não permitirem a renúncia a direitos morais, em vez disso, você concederá à ADS Store o direito de usar o Seu Conteúdo assim como todos os elementos do Seu Conteúdo, com ou sem seu nome ou pseudônimo, bem como o direito de editar livremente o Seu Conteúdo.</li>
<li>Você declara, garante e concorda que nenhuma parte de Seu Conteúdo estará sujeita a qualquer obrigação, seja de confidencialidade, atribuição ou de outra forma, por parte da ADS Store, sendo que a ADS Store não será responsável por qualquer uso ou divulgação do Seu Conteúdo.</li>
<li>Você ainda declara, garante e concorda que o Seu Conteúdo não violará nenhum direito de terceiros.</li></ol>
<header><h2>9. MONITORAMENTO & ANTI-TRAPAÇA</h2></header>
<h4>9.1. <u>A ADS Store me monitora enquanto utilizo os Serviços da ADS Store</u> (Sim. Leia a Política de Privacidade para saber mais.)</h4>
<p>Política de Privacidade para saber detalhes importantes sobre como obtemos e processamos informações relativamente ao uso dos Serviços da ADS Store.</p>

<p>9.2. <u>A ADS Store executa programas no meu dispositivo enquanto não estou usando os Serviços da ADS Store? (Podemos, para fins anti-trapaça limitados.)</u></p>
<p>Para evitar trapaças e hackers, podemos exigir que você instale um software anti-trapaça. Este software pode ser executado em segundo plano no seu dispositivo.</p>
<header><h2>10. ATUALIZAÇÕES E MODIFICAÇÕES</h2></header>
<h4>10.1. <u>Esses Termos serão alterados no futuro?</u> (Sim.)</h4>
<p>Podemos criar (e provavelmente criaremos) versões atualizadas destes Termos no futuro, à medida que os Serviços da ADS Store e as leis aplicáveis evoluírem. Quando o fizermos, informaremos você sobre o novo contrato que substituirá estes Termos. Você terá a oportunidade de analisar qualquer novo contrato que lhe apresentarmos e decidir se deseja concordar com os termos revistos. Se você aceitar o novo contrato, poderá continuar usando os Serviços da ADS Store. Se você recusar o novo contrato, não poderá mais usar os Serviços da ADS Store.</p>
<h4>10.2. <u>Os serviços da ADS Store permanecerão os mesmos?</u> (Não. Como Kha'zix, eles evoluirão.)</h4>
<p>Em um esforço para melhorar constantemente os Serviços da ADS Store, promover a evolução de nossos jogos e manter os Serviços da ADS Store seguros, divertidos e protegidos, você concorda que podemos alterar, modificar, atualizar, suspender, “nerf” ou restringir seu acesso a quaisquer recursos ou partes dos Serviços da ADS Store, inclusive os Produtos Virtuais (por exemplo, podemos alterar alguns recursos dos Produtos Virtuais por razões regulatórias ou legais ou para melhorar a experiência do jogo) e podemos exigir que você baixe e instale softwares e atualizações de qualquer software necessário para suportar o ADS Store Services, a qualquer momento, sem responsabilidade para você. Você também entende e concorda que essas alterações ou atualizações dos Serviços da ADS Store podem alterar as especificações de sistema necessárias para jogar nossos jogos e, nesse caso, você, e não a ADS Store, será responsável por comprar qualquer software ou hardware adicional necessário para acessar e jogar nossos jogos. Você também entende e concorda que podemos usar patches em segundo plano para atualizar automaticamente nossos jogos e software com ou sem aviso prévio.</p>
<header><h2>11. LINKS</h2></header>
<h4>11.1. <u>E quanto aos links nos Serviços da ADS Store? São seguros?</u> (Como as viagens mágicas de Bardo, você poderá encontrar algo perigoso esperando por você do outro lado. Prossiga com cuidado….)</h4>
<p>Os Serviços da ADS Store podem conter links para sites operados por terceiros. Novamente, não possuímos nem operamos esses outros sites. Nós fornecemos esses links para sua conveniência, ou outros usuários podem estar postando esses links como conteúdo fornecido pelo usuário. Use esses links e os sites externos correspondentes por sua conta e risco. Não controlamos os sites linkados e não somos responsáveis pelo conteúdo disponível neles. Esses links não implicam nosso endosso de informações ou materiais em qualquer outro site, e não assumimos nenhuma responsabilidade em relação ao acesso e uso que você fizer desses sites vinculados.</p>
<header><h2>12. AVISO E PROCEDIMENTO PARA RECLAMAÇÕES POR VIOLAÇÃO DE DIREITOS AUTORAIS</h2></header>
<h4>12.1. <u>O que devo fazer se alguém estiver violando meu trabalho protegido por direitos autorais nos Serviços da ADS Store?</u> (Envie-nos um aviso de remoção de direitos autorais.)</h4>
<p>A ADS Store respeita a lei de direitos autorais e espera que seus usuários façam o mesmo. Nossa política é encerrar, em circunstâncias apropriadas, as contas de usuários que violam ou se acredita que violem direitos de titulares de direitos autorais. A ADS Store responderá celeremente às reclamações de que houve violação de direitos autorais cometidas usando o site da ADS Store ou outra rede on-line acessível através de um dispositivo móvel ou outro tipo de dispositivo (os “Sites”) que são reportados ao Agente de Direitos Autorais Designado da ADS Store, identificado no modelo de notificação abaixo.</p>
<p>Se você é um proprietário de direitos autorais, ou está autorizado a agir em nome de um ou proprietário de direitos autorais, ou ainda, está autorizado a agir amparado por qualquer direito autoral exclusivo, denuncie as supostas violações de direitos autorais que ocorrem nos Sites ou através desses, enviando uma notificação que contenha todos os seguintes itens:</p>
<ol><li>Identifique o trabalho protegido por direitos autorais que você alega ter sido violado ou - se vários trabalhos protegidos por direitos autorais estiverem abrangidos por esta Notificação - você poderá fornecer uma lista representativa dos trabalhos protegidos por direitos autorais que você alega terem sido violados.</li>
<li>Identifique o material que você alega estar infringindo (ou que seja objeto de atividade infratora) e que deva ser removido ou cujo acesso deva ser desativado e informações razoavelmente suficientes para nos permitir localizar o material, inclusive no mínimo, se aplicável, o endereço [URL] do link mostrado no(s) Site (s) onde esse material pode ser encontrado.</li>
<li>Forneça seu endereço para correspondência, número de telefone e, se disponível, endereço de e-mail.</li>
<li>Inclua as duas declarações a seguir no corpo da Notificação:
<ol><li>“Declaro, de boa fé, que o uso contestado do material protegido por direitos autorais não está autorizado pelo proprietário dos direitos autorais, por seu agente nem pela lei (p. ex., como ‘fair use’ (limitação de direitos autorais).”</li>
<li>“Declaro que as informações nesta Notificação são exatas e [sob pena de falso testemunho] * que sou o proprietário ou estou autorizado a agir em nome do proprietário do direito autoral ou de um direito exclusivo ao amparo do direito autoral que supostamente foi violado.”</li></ol></li>
<li>Forneça seu nome completo e sua assinatura eletrônica ou física..</li></ol>
<p>* Você só precisa incluir esse trecho se morar nos Estados Unidos da América.</p>
<p>Entregue esta notificação (“<strong>Notificação</strong>”), com todos os itens preenchidos, ao Agente de Direitos Autorais da ADS Store no endereço da empresa da ADS Store responsável por fornecer os Serviços da ADS Store em sua região (consulte a <a href="#id.dhzr7hbtlg9b">Cláusula 19</a>). Não se esqueça de marcar “A/C: Agente de Direitos Autorais” (e não “A/C: Departamento Jurídico) para que ela chegue rapidamente à pessoa certa. Em vez disso, você pode enviar sua Notificação por e-mail para: copyright@ADS Storegames.com. Esse endereço de e-mail destina-se exclusivamente ao recebimento de notificações de remoção por violação a direitos autorais e não para consultas gerais ou pedidos para a ADS Store. Anexos não podem ser aceitos no endereço de e-mail por motivos de segurança. Sendo assim, qualquer Notificação enviada eletronicamente com um anexo não será recebida nem processada.</p>
<p>Observe que as Notificações são avisos legais e que a ADS Store pode fornecer cópias desses avisos aos participantes no conflito ou a terceiros, a seu critério ou conforme exigido por lei. Ao receber tal Notificação, a ADS Store tomará qualquer medida que, a seu critério exclusivo, considerar apropriada, inclusive a remoção, dos Sites, do material em questão.</p>
<header><h2>13. ISENÇÃO DE GARANTIA</h2></header>
<h4>13.1. <u>A ADS Store oferece garantias sobre os Serviços da ADS Store?</u> (Depende de onde você está -- prepare-se para mais advogados gritando!)</h4>
<p><u><strong>Você assume toda a responsabilidade pela instalação e utilização, bem como pelos resultados obtidos a partir dos Serviços da ADS Store (não importa onde você esteja situado).</strong></u></p>
<p>Além disso, se você estiver sediado na América do Norte, Central ou do Sul::</p>
<p><u><strong>Os Serviços da ADS Store são fornecidos a você "no estado em que se encontram" e "conforme disponíveis", sem garantias ou declarações de qualquer tipo, expressas ou implícitas. Você assume total responsabilidade pelo uso que fizer dos Serviços da ADS Store. Na medida máxima permitida pela lei aplicável, a ADS Store exime-se de prestar todas as garantias, expressas ou implícitas, que possam se aplicar aos Serviços da ADS Store, inclusive garantias implícitas de titularidade, não violação, garantia de comercialização, adequação a uma finalidade específica, e quaisquer garantias decorrentes de negociação, durante o desempenho ou prática inerente ao negócio, bem como qualquer garantia quanto à precisão, à confiabilidade ou à qualidade de qualquer conteúdo ou informação contida nos Serviços da ADS Store.</strong></u></p>
<header><h2>14. INDENIZAÇÃO</h2></header>
<h4>14.1. <u>Se alguém processar a ADS Store com base no meu uso ou uso indevido dos Serviços da ADS Store, tenho que pagar pelas despesas legais da ADS Store?</u> (Sim.)</h4>
<p>Na medida do permitido por lei, exceto em casos que envolvam negligência grave ou dolo de nossa parte, você desde já concorda em indenizar, defender e manter a ADS Store, bem como suas subsidiárias, afiliadas, diretores e conselheiros, isentos de responsabilidade quanto a todas e quaisquer reivindicações, ações judiciais, perdas, passivos e custos que surgirem ou resultarem do uso indevido dos Serviços da ADS Store, qualquer violação de alguma das disposições destes Termos (por exemplo, se você usar hacks, cheats ou bots nos Serviços da ADS Store ou infringir nossos direitos de PI) ou qualquer violação dos direitos de terceiros cometida por você. A ADS Store reserva-se o direito de, às suas próprias custas e a seu exclusivo e absoluto critério, assumir a defesa e o controle exclusivos de qualquer assunto eventualmente sujeito a indenização de sua parte; caso em que você cooperará com a ADS Store para fazer valer quaisquer defesas disponíveis.</p>
<p>Por exemplo, se você usar os Serviços da ADS Store como parte de uma operação comercial (algo que você não tem permissão para fazer) e nós formos processados por algo que você fizer e que afrontar estes Termos, você deverá nos defender em juízo e pagar por quaisquer danos nos quais incorrermos.</p>
<header><h2>15. LIMITAÇÃO DE RESPONSABILIDADE</h2></header>
<h4>15.1. <u>Existe um limite para a responsabilidade potencial da ADS Store segundo estes Termos?</u> (Sim.)</h4>
<p><u><strong>Na medida permitida por lei, nossa responsabilidade total perante você (seja por violação deste contrato, negligência ou por qualquer outro motivo) por qualquer perda, lesão ou dano sofrido por você com relação ao download, uso e/ou acesso aos Serviços da ADS Store, é limitada aos valores totais pagos por você à ADS Store durante os 6 (seis) meses imediatamente anteriores ao momento em que sua causa de pedir surgiu pela primeira vez.</strong></u></p>
<p><u><strong>Disponibilizamos apenas os Serviços da ADS Store para uso doméstico e privado. Não nos responsabilizamos por perdas comerciais (como lucros cessantes, perda de negócios, interrupção de negócios, perda de fundo de comércio ou perda de oportunidade de negócios). Também não nos responsabilizamos por qualquer dano que ocorra porque você não instalou nenhuma atualização quando ela é disponibilizada pela ADS Store ou quando você deixa de manter as especificações mínimas do sistema necessárias. Separadamente, não somos responsáveis por: (i) qualquer perda que não era previsível no momento em que você aceitou estes Termos; ou (ii) qualquer perda que nós dois sabíamos que poderia ocorrer apenas devido às suas circunstâncias especiais existentes no momento em que você aceitou estes Termos (inclusive todos os danos indiretos).</strong></u></p>
<p><u><strong>Não obstante qualquer disposição em contrário nestes Termos, NÃO EXCLUÍMOS NEM LIMITAMOS, DE FORMA ALGUMA, NOSSA RESPONSABILIDADE PARA COM VOCÊ QUANDO SERIA ILEGAL FAZÊ-LO, inclusive nossa responsabilidade por: (i) morte ou lesão corporal decorrente de nossa negligência; (ii) fraude ou declaração fraudulenta de nossa parte; (iii) comportamento negligente ou doloso; (iv) por danos decorrentes de uma violação negligente de uma obrigação que seja essencial para a execução do contrato pela ADS Store (“Deveres Essenciais”) na medida em que seja típico e previsível; (v) por qualquer garantia prestada por nós a você; ou (vi) por qualquer responsabilidade nos termos da legislação aplicável a responsabilidade por produto em uma região.</strong></u></p>
<p><u><strong>Você também pode ter direitos específicos segundo a legislação local, além dos descritos acima.</strong></u></p>
<header><h2>16. LEI APLICÁVEL</h2></header>
<h4>16.1. <u>Qual lei se aplica a estes Termos ou no caso de algum conflito?</u> (Isso depende de onde você mora e de qual empresa da ADS Store fornece os Serviços da ADS Store a você.)</h4>
<p>Leia abaixo para determinar qual legislação se aplica ao seu uso dos Serviços da ADS Store. Independentemente de qual seja o direito aplicável, você pode ter o benefício da aplicação de outros direitos ou da aplicação de direitos ou medidas obrigatórias adicionais previstas na legislação local, além daquelas estabelecidas nestes Termos. Nada nestes Termos limita ou afeta esses direitos.</p>

<p><strong>Se você mora na América do Norte, Central ou do Sul (exceto o Brasil)</strong></p>
<p>Estes Termos e qualquer ação decorrente ou em conexão com estes Termos serão regidos pela Lei Federal de Arbitragem em relação à <a href="#id.7x2afytv2ia0">Cláusula 17</a> “Resolução de Conflitos" e às leis do Estado da Califórnia, sem considerar as disposições sobre conflito de leis. Salvo disposição em contrário expressamente prevista na <a href="#id.7x2afytv2ia0">Cláusula 17</a></p>
<p><u><strong>Se você mora na Coréia do Sul</strong></u></p>
<p><strong>Estes Termos e qualquer ação decorrente de ou relacionada a estes Termos serão regidos pelas leis da Coréia.</strong></p>
<p><strong>Se você mora no Japão</strong></p>
<p><strong>Estes Termos e qualquer ação decorrente de ou relacionada a estes Termos serão regidos pelas leis do Japão.</strong></p>
<p><strong>Se você mora em Cingapura, Filipinas, Tailândia, Malásia, Indonésia e Camboja ("Sudeste Asiático")</strong></p>
<p><strong>Estes Termos e qualquer ação decorrente de ou relacionada a estes Termos serão regidos pelas leis de Cingapura.</strong></p>
<p><u><strong>Se você mora no Espaço Econômico Europeu, no Reino Unido, no Brasil ou em qualquer país que não esteja listado nesta </strong></u><a href="#id.qrx9xp3diysn"><strong>Cláusula 16</strong></a></p>
<p>Estes Termos e qualquer ação decorrente de ou relacionada a estes Termos serão regidos e interpretados segundo as leis da Irlanda, sem considerar os princípios de conflito de leis no espaço.</p>
<header><h2>17. RESOLUÇÃO DE CONFLITOS</h2></header>
<h4>17.1. <u>Tenho um problema que não consegui resolver com a ADS Store. Qual é o caminho para resolver essa questão?</u> (Isso depende de onde você mora)</h4>
<p>Se você mora:</p>
<p><a href="https://www.ADS Storegames.com/pt-br/terms-of-service-BR#parteA" target="_blank">Parte A</a></p>
<ul><li><strong>Na América do Norte, Central ou do Sul (exceto o Brasil)</strong>, você estará contratando e lidando com a ADS Store Inc. e precisará ler a <a href="#id.j1y4x7y5qxxs">Parte A</a> (Termos Gerais para Resolução de Conflitos) e a <a href="#id.a0gr2qd6kj6t">Parte B</a> desta Cláusula;</li>
<li><strong>Na Corréia do Sul</strong>, você estará contratando e lidando com a ADS Store Korea Limited e precisará ler a <a href="#id.j1y4x7y5qxxs">Parte A</a> Termos Gerais para Resolução de Conflitos) e a <a href="#id.g3b7aqf3986d">Parte C</a> desta Cláusula;</li>
<li><strong>No Japão</strong>, você estará contratando e lidando com a ADS Store, LLC e precisará ler a <a href="#id.j1y4x7y5qxxs">Parte A</a> (Termos Gerais de Resolução de Conflitos) e a <a href="#id.75wvpuk58gxu">Parte D</a> desta Cláusula;</li>
<li><strong>No Sudeste Asiático</strong>, você estará contratando e lidando com a ADS Store Services PTE. LTD. e você precisa ler a <a href="#id.j1y4x7y5qxxs">Parte A</a> (Termos Gerais de Resolução de Conflitos) e a <a href="#id.7edudat2juf1">Parte E</a> desta Cláusula; ou</li>
<li><strong>No Espaço Econômico Europeu, Reino Unido, Brasil ou qualquer outra região/país que não esteja listado acima</strong>,você estará contratando e negociando com a ADS Store Limited e precisará ler a <a href="#id.j1y4x7y5qxxs">Parte A</a> Termos Gerais de Resolução de Conflitos). Se você reside na UE, a <a href="#id.qmcjibs1weo9">Parte F</a> desta Cláusula também será aplicável</li></ul>
<h4><em>Parte A: Termos Gerais de Resolução de Conflitos (não importa onde você mora)</em></h4>
<h4>17.2. <u>Se tivermos um conflito, podemos usar o modo 1 v 1?</u> (Não, devemos negociar primeiro.)</h4>
<p>Conflitos podem ser caros e demorados para ambas as partes (a justiça não vem voando rapidamente fora de Valoran). Em um esforço para acelerar a resolução (“<strong>Reclamação</strong>”), você e a ADS Store concordam em primeiro tentar negociar informalmente qualquer Reclamação por pelo menos 30 (trinta) dias (exceto conforme definido na <a href="#id.3ftrnjnd5ul6">Cláusula 17.4</a> below).</p>
<h4>17.3. <u>Como a negociação começa?</u> (Um de nós envia ao outro uma notificação por escrito descrevendo a situação e a pretensão.)</h4>
<p>A ADS Store enviará uma notificação para o endereço de e-mail associado à sua conta. Se você não tiver uma conta na ADS Store, enviaremos a notificação para o endereço de e-mail que você usou para nos escrever sobre a Reclamação. Você deve enviar sua notificação à empresa da ADS Store responsável por fornecer-lhe os Serviços da ADS Store (consulte a <a href="#id.dhzr7hbtlg9b">Cláusula 19</a> para obter detalhes de contato). Observe que este procedimento informal de resolução não suspende nenhum prazo legal de prescrição aplicável à apresentação de uma Reclamação.</p>
<h4>17.4. <u>Quais reclamações estamos concordando em submeter a negociação?</u> (Depende do tipo de conflito)</h4>
<p>Na medida máxima permitida pela lei aplicável e sem limitar seus direitos legais de ajuizar um processo judicial, você e a ADS Store concordam que as seguintes Reclamações não estão sujeitas às outras disposições desta <a href="#id.j1y4x7y5qxxs">Parte A</a> relativas às negociações: (i) quaisquer Reivindicações que pretendam exigir o cumprimento ou proteger, ou sejam relativas à validade de qualquer um dos seus direitos de propriedade intelectual ou dos direitos de propriedade intelectual da ADS Store; (ii) qualquer Reclamação relacionada a, ou resultante de, alegações de roubo, pirataria, invasão de privacidade ou uso não autorizado; e (iii) qualquer Reclamação de tutela de equidade (p. ex., uma ordem judicial). Além disso, qualquer uma das partes pode propor uma ação no juizado especial (pequenas causas) no caso de Reclamações que estejam sob a competência de tais juízos.</p>
<h4><em>Parte B: Resolução de conflitos na América do Norte, Central ou do Sul (exceto o Brasil)</em></h4>
<h4>17.5. <u>O que é esse negócio de arbitragem? </u>(Um método particular de solução de conflitos. Não há tribunais nem júris.)</h4>
<p>A arbitragem é um processo alternativo de resolução de conflitos, no qual as partes concordam em ter suas controvérsias decididas por um terceiro neutro e não por um juiz ou júri. A arbitragem permite que as partes resolvam suas divergências em particular e sem a formalidade de ir a um tribunal. A arbitragem segue regras processuais diferentes das de um tribunal e está sujeita a uma revisão muito limitada pelos tribunais.</p>
<h4>17.6. <u>A arbitragem permitirá o mesmo tipo de resultado que um tribunal? </u>(Sim.)</h4>
<p>O árbitro terá o poder de conceder qualquer tipo de provimento jurisdicional ou de equidade que estaria disponível em um tribunal competente. A decisão do árbitro (denominada “<strong>Sentença Arbitral</strong>”) consistirá em uma declaração escrita indicando a decisão adotada sobre cada reclamação e fornecerá uma declaração escrita concisa das constatações e conclusões essenciais nas quais a Sentença Arbitral se baseia. A Sentença Arbitral será definitiva e obrigará as partes, podendo ser homologada por um tribunal competente e, em seguida, aplicada como qualquer outra ordem ou sentença judicial.</p>
<h4>17.7.<u> Quais reclamações estamos concordando em submeter à arbitragem?</u> (Quase tudo.)</h4>
<p>Qualquer conflito, reclamação ou controvérsia decorrente de ou relacionada a estes Termos ou aos Serviços da ADS Store será resolvido exclusivamente por arbitragem vinculativa e privada, e não em juízo, ressalvado que ações de pequeno valor poderão ser propostas em juizados especiais (pequenas causas) e qualquer uma das partes poderá buscar tutela de emergência, cautelar, antes da nomeação de um árbitro, conforme especificado na <a href="#id.djtp0mf89wj3">Cláusula 17.14</a> abaixo. . Isso significa que, exceto para reclamações de pequeno valor e situações de emergência cobertas pela <a href="#id.djtp0mf89wj3">Cláusula 17.14</a> você e a ADS Store renunciam ao direito de levar tais reclamações perante uma autoridade judicial, inclusive o direito a um julgamento por júri..</p>
<h4>17.8. <u>Posso apresentar uma reclamação em uma ação coletiva ou popular?</u> (Não. Desculpe por mais gritos de advogados, mas isso é muito importante.)</h4>
<p><u><strong>Você e a ADS Store concordam que cada um de nós pode mover ações contra o outro apenas em caráter individual e não como um autor ou membro de alguma classe em qualquer suposta ação coletiva ou processo representativo. A menos que você e a ADS Store concordem em contrário, o árbitro não poderá consolidar ou reunir mais de uma reclamação de uma pessoa ou parte, e não poderá presidir qualquer forma de processo consolidado, representativo ou coletivo. Além disso, o árbitro pode conceder uma medida (inclusive sobre assunto monetário, de caráter liminar e declaratório) apenas em favor da parte individual que buscar tal prestação e apenas na medida necessária para fornecer o provimento pleiteado nas reivindicações individuais dessa parte.</strong></u></p>
<h4>17.9. <u>Quais questões o árbitro decidirá?</u> (Praticamente tudo.)</h4>
<p>O árbitro decidirá todas as controvérsias entre você e a ADS Store.</p>
<h4>17.10. <u>Quem administrará a arbitragem?</u> (JAMS, usando suas “Regras e Procedimentos Abrangentes de Arbitragem.”)</h4>
<p>A arbitragem será administrada pela <a href="https://www.jamsadr.com/" target="_blank">JAMS</a> de acordo com suas <a href="https://www.jamsadr.com/rules-comprehensive-arbitration/" target="_blank">Regras e Procedimentos Abrangentes de Arbitragem</a> (“<strong>Regras da JAMS</strong>”). AUm único árbitro será selecionado de acordo com essas regras. A Sentença Arbitral poderá ser homologada em qualquer tribunal competente.</p>
<h4>17.11. <u>Como se inicia uma arbitragem?</u> (Um de nós envia ao outro e à JAMS uma notificação por escrito descrevendo a situação e o pedido)</h4>
<p>Qualquer uma das partes pode iniciar um processo de arbitragem. A parte que inicia a arbitragem é chamada de "requerente". Uma parte que deseja iniciar a arbitragem deve enviar um Requerimento de Arbitragem por escrito à JAMS e notificar a outra parte. A JAMS fornece um formulário de Requerimento de Arbitragem em seu <a href="https://www.jamsadr.com/" target="_blank">site</a>.</p>
<h4>17.12. <u>Quem vai pagar pela arbitragem?</u> (Pagamos taxas de registro para reclamações menores, mas você deve pagar as taxas para reclamações de valores mais elevados. Não exigiremos que você pague honorários advocatícios pela arbitragem a menos que sua reclamação seja considerada temerária.)</h4>
<p>O pagamento de todas as taxas de registro e administração da arbitragem e dos honorários do árbitro será regido pelas Regras da JAMS. Pagaremos todas as taxas e despesas de registro, administração e honorários do árbitro se seu pleito for inferior a US$10.000, a menos que o árbitro considere sua reclamação temerária. Se formos vitoriosos na arbitragem, pagaremos todos os honorários e custos de nossos advogados e não exigiremos reembolso de você. Se você vencer, terá direito a uma determinação de pagamento de honorários e despesas de advogados, na medida prevista pela lei aplicável.</p>
<h4>17.13. <u>Onde e como ocorrerá a arbitragem?</u> (Por telefone, por escrito ou em sua cidade - você escolhe.)</h4>
<p>Você poderá optar por realizar a arbitragem por telefone, com base em documentação escrita, pessoalmente no município onde mora ou em outro local escolhido por acordo mútuo.</p>
<h4>17.14. <u>E quanto à violação de propriedade intelectual?</u> (Qualquer uma das partes pode ajuizar uma ação com o objetivo limitado de buscar uma medida “cautelar”.)</h4>
<p>Qualquer uma das partes pode buscar soluções provisórias de emergência, inclusive medidas liminares ou semelhantes, de acordo com as regras da JAMS ou de um tribunal competente localizado no Condado de Los Angeles, Califórnia, quando necessário para proteger os direitos e interesses dessa parte no caso de violação ou apropriação indevida de direitos de propriedade intelectual até a nomeação de um árbitro.</p>
<h4>17.15. <u>Qualquer um de nós pode contar a nossos amigos e seguidores do Twitter sobre a arbitragem?</u> (Não.)</h4>
<p>Você e a ADS Store concordam que qualquer disputa, reclamação ou controvérsia que tenha sido submetida à arbitragem bem como todos os procedimentos relacionados, inclusive qualquer acordo, serão mantidos em sigilo. Contudo, a parte vencedora em qualquer arbitragem poderá submeter a Sentença Arbitral a qualquer tribunal competente de maneira que a Sentença Arbitral seja homologada por meio de uma ordem ou determinação judicial.</p>
<h4>17.16. <u>E se parte deste compromisso arbitral não for aplicável?</u> (O restante permanece válido - nós mantemos o máximo possível dele que possa ser cumprido nos termos da lei.)</h4>
<p>Você e a ADS Store concordam que, se qualquer parte deste compromisso arbitral for declarado inexequível, essa parte será removida e o restante deste compromisso permanecerá em pleno vigor. Todavia, se a <a href="#id.ez7q8kbncgp0">Cláusula 17.8</a>, acima (intitulada "Posso apresentar uma reclamação em uma ação coletiva ou popular?") ou qualquer parte dela for considerada inexequível, todo este compromisso arbitral (ou seja, toda a <a href="#id.j1y4x7y5qxxs">Parte A da Cláusula 17</a>)deverá ser desvinculado destes Termos e todas as reclamações entre você e a ADS Store serão decididas exclusivamente por um tribunal localizado no Condado de Los Angeles, Califórnia, conforme estabelecido na parte pertinente da <a href="#id.qrx9xp3diysn">Cláusula 16</a> acima.</p>
<h4><em>Parte C: Resolução de conflitos para a Coréia do Sul</em></h4>
<p>Qualquer demanda que surgir segundo estes Termos ou os Serviços da ADS Store será ajuizada no juízo competente, de acordo com o Código de Processo Civil coreano.</p>
<h4><em>Parte D: Resolução de conflitos no Japão</em></h4>
<p>O Tribunal Distrital de Tóquio terá a jurisdição exclusiva em primeira instância sobre qualquer conflito entre a ADS Store e você decorrente destes Termos ou com relação a eles ou a quaisquer Serviços da ADS Store.</p>
<h4><em>Parte E: Resolução de conflitos para o Sudeste Asiático</em></h4>
<p>Qualquer conflito, controvérsia, reclamação ou diferença de qualquer natureza decorrente de ou relacionada a estes Termos ou aos Serviços da ADS Store deverá ser encaminhada e definitivamente resolvida por arbitragem conduzida pelo Centro Internacional de Arbitragem de Cingapura (“<strong>SIAC</strong>”) de acordo com as Regras de Arbitragem do Centro Internacional de Arbitragem de Cingapura (“<strong>Regras do SIAC</strong>”) vigentes, regras essas que são consideradas incorporadas nesta Cláusula por referência. A sede da arbitragem será Cingapura. O Tribunal Arbitral será composto por três (3) árbitros e o idioma da arbitragem será o inglês</p>
<h4><em>Parte F: Resolução de conflitos para residentes do EEE</em></h4>

<h4>17.17. <u>Tenho outras opções de resolução de conflitos?</u></h4>
<p>Se você mora dentro do Espaço Econômico Europeu, poderá encaminhar a controvérsia para a <a href="https://ec.europa.eu/consumers/odr/main/index.cfm?event=main.home.chooseLanguage" target="_blank">Plataforma de Resolução de Litígios da Comissão Europeia </a>(consulte ec.europa.eu/consumers/odr).</p>
<p>Dentro de um ano após o envio de sua reclamação, você também poderá tentar resolver sua controvérsia com a ADS Store através de um procedimento de mediação. Isso não limita seus direitos legais de ajuizar um processo judicial.</p>
<header><h2>18.TERMOS ADICIONAIS APLICÁVEIS AOS SERVIÇOS DA ADS Store</h2></header>
<h4>18.1. <u>Termos gerais</u></h4>
<p>Você pode acessar os Serviços da ADS Store que disponibilizamos a partir de determinadas lojas ou plataformas de terceiros autorizados (um terceiro provedor autorizado de qualquer loja, sistema de jogo, console ou plataforma, ora denominados, individualmente, “<strong>Plataforma de Terceiros</strong>”), somente se você concordar que:</p>
<ul><li>Estes Termos são um acordo entre nós e você, e não entre você e a Plataforma de Terceiros. Entre a ADS Store e a Plataforma de Terceiros, a ADS Store é responsável unicamente por quaisquer Serviços da ADS Store.</li>
<li>A Plataforma de Terceiros não tem obrigação de fornecer serviços de manutenção e suporte para os Serviços da ADS Store.</li>
<li>A Plataforma de Terceiros não é responsável por tratar de quaisquer reivindicações suas relacionadas aos Serviços da ADS Store ou à sua posse e seu uso do Serviço da ADS Store.</li>
<li>Se um terceiro alegar que qualquer um dos Serviços da ADS Store infringe os direitos de propriedade intelectual da outra parte, como entre a Plataforma de Terceiros e a ADS Store, a Plataforma de Terceiros não será responsável pela investigação, defesa, resolução e extinção de qualquer reclamação.</li>
<li>A Plataforma de terceiros e suas subsidiárias são terceiros beneficiários destes Termos, na medida em que digam respeito à sua licença dos Serviços da ADS Store. Após sua aceitação destes Termos, a Plataforma de Terceiros terá o direito (e será considerado que aceitou o direito) de exigir o cumprimento desta <a href="#id.qhjqi6j9gbr2">Cláusula 18</a> e da <a href="#id.o1c27fyx5l9o">Cláusula 20.9</a> em relação à sua licença dos Serviços da ADS Store contra você na qualidade de terceiro beneficiário.</li>
<li>Você também deverá observar todos os termos de serviço e licenças de terceiros aplicáveis ao acessar ou usar a Plataforma de Terceiros, inclusive quaisquer termos adicionais que se apliquem ao baixar, transmitir, acessar ou usar qualquer jogo da ADS Store, o Conteúdo Virtual ou os demais Serviços da ADS Store.</li></ul>
<header><h2>19. PESSOAS JURÍDICAS DA ADS Store</h2></header>
<p>Se você mora em qualquer lugar da América do Norte, Central ou do Sul (exceto Brasil):<br/>ADS Store, Inc.<br/>Attn: Legal Department<br/>12333 West Olympic Blvd.<br/>Los Angeles, CA 90064<br/>United States</p>

<p>Se você mora na Coréia do Sul:</p>
<p>ADS Store Korea, Ltd.<br/>Attn: Legal Department<br/>30th floor, Parnas Tower, 521 Teheran-ro, Gangnam-gu<br/>Seoul, Korea</p>

<p>Se você mora no Japão:</p>
<p>ADS Store, LLC<br/>Attn: Legal Department<br/>Roppongi Hills Mori Tower 34F<br/>6-10-1, Roppongi, Minato-ku,<br/>Tokyo 106-6134<br/>Japan</p>

<p>Se você mora no Sudeste Asiático:</p>
<p>ADS Store Services PTE. LTD.<br/>Attn: Legal Department<br/>51 Bras Basah Rd, #05-01, S5008 & S5009,<br/>Singapore 189554</p>

<p>Se você mora em outro lugar, incluindo EEE, Reino Unido ou Brasil:</p>
<p>ADS Store Ltd.<br/>Attn: Legal Department<br/>PO Box 11989<br/>Dublin 2<br/>Ireland</p>
<header><h2>20. DISPOSIÇÕES GERAIS</h2></header>
<h4>20.1. <u>O que posso fazer se tiver dúvidas sobre os Serviços da ADS Store?</u> (Até o dia em que estabelecermos um call center em Yordle, você poderá nos enviar um e-mail.)</h4>
<p>Se você tiver alguma dúvida sobre os Serviços da ADS Store, ou se desejar entrar em contato conosco por qualquer outro motivo, entre em contato com o suporte da ADS Store no endereço <a href="https://support.ADS Storegames.com/hc/pt-br" target="_blank">https://support.ADS Storegames.com/hc/pt-br</a></p>
<h4>20.2. <u>Qualquer uma das partes pode ceder esses Termos?</u> (Não. Apenas nós.)</h4>
<p>A ADS Store poderá ceder seus direitos segundo estes Termos, no todo ou em parte, a qualquer pessoa física ou jurídica, a qualquer momento, com ou sem o seu consentimento. Você não poderá ceder seus direitos segundo estes Termos sem o consentimento prévio por escrito da ADS Store, e qualquer cessão não autorizada que você fizer será nula de pleno direito.</p>
<h4>20.3. <u>Este é todo o nosso acordo?</u> (Sim, inclusive as outras políticas importantes sobre as quais falamos anteriormente.)</h4>
<p>Estes Termos representam o acordo integral entre você e a ADS Store em relação aos Serviços da ADS Store, e substituem quaisquer acordos anteriores ou contemporâneos entre você e a ADS Store. Estes Termos coexistirão com, e não substituirão quaisquer outras políticas da ADS Store referenciadas nestes Termos. Você e a ADS Store concordam que cada um de nós não se baseou em quaisquer termos, condições, declarações, garantias ou similares que não estejam expressamente estabelecidos nestes Termos e nem teremos quaisquer recursos legais em relação a tais termos, condições, declarações, garantias ou similares que não estão expressamente estabelecidos nesses Termos.</p>
<h4>20.4. <u>O que acontece se um desastre natural interferir no Jogo</u> (A ADS Store não é responsável.)</h4>
<p>A ADS Store não se responsabiliza por qualquer atraso ou falha no seu desempenho, inclusive qualquer falha no seu cumprimento do disposto nestes Termos, em razão de circunstâncias imprevistas ou causas fora do controle da ADS Store, tais como: (a) hacking, ataques cibernéticos, corrupção/perda de dados (quando tivermos tomado as medidas que deveriam ser tomadas por empresas como a nossa para evitar essa ocorrência); ou (b) casos fortuitos, guerra, terrorismo, ameaças de bomba, tumultos, embargos, atos de autoridades civis ou militares, incêndio, inundações, acidentes, greves ou escassez de recursos de transporte, combustível, energia, mão de obra ou materiais.</p>
<h4>20.5. <u>Esses Termos significam que somos parceiros?</u> (Não no sentido legal, não.)</h4>
<p>Você concorda que não existe relação de joint venture, parceria, vínculo empregatício ou representação entre você e a ADS Store em decorrência destes Termos ou do uso dos Serviços da ADS Store.</p>
<h4>20.6. <u>Se eu violar estes Termos e a ADS Store não fizer nada por um longo tempo, isso significa que me livrei da responsabilidade?</u> (Não. Reservamos todos os nossos direitos.)</h4>
<p>O fato de a ADS Store deixar de exigir o cumprimento de qualquer disposição destes Termos não deve ser interpretado como uma renúncia presente ou futura a essa disposição, nem de maneira alguma afetará o direito de qualquer parte de exigir o cumprimento de cada uma dessas disposições posteriormente. Qualquer renúncia da ADS Store a qualquer disposição, condição ou exigência destes Termos não constituirá uma renúncia a qualquer obrigação futura de cumprir tal disposição, condição ou exigência.</p>
<h4>20.7. <u>Quais recursos estão disponíveis para a ADS Store se eu violar estes Termos?</u></h4>
<p>Você concorda que a ADS Store sofreria danos irreparáveis se uma violação de alguns destes Termos (como a <a href="#id.xyyxssr12ehd">Cláusula 3.2</a>) não fosse punida especificamente e que a indenização por danos não seria um recurso jurídico suficiente para a ADS Store em decorrência disso. Podemos nos basear nesta Cláusula para pleitear em juízo uma ordem judicial ou execução específica.</p>
<h4>20.8. <u>Se eu precisar enviar uma notificação legal para a ADS Store, para onde o envio?</u> (Esperamos que você nunca precise nos enviar uma, mas se o fizer ...)</h4>
<p>Salvo o expressamente disposto em contrário nestes Termos, todas as notificações enviadas por você ou exigidas nestes Termos deverão ser feitas por escrito e endereçadas à empresa da ADS Store que fornece os Serviços ADS Store em questão. Veja a <a href="#id.dhzr7hbtlg9b">Cláusula 19 </a>para o endereço da empresa da ADS Store pertinente.</p>
<h4>20.9. <u>Posso jogar o Jogo se o governo dos EUA achar que eu talvez seja um terrorista ou se eu morar em um país sujeito a embargo?</u> (Não.)</h4>
<p>Grande parte dos Serviços da ADS Store são desenvolvidos nos EUA, então você não poderá utilizá-los se: (1) o Escritório de Controle de Ativos Estrangeiros do Departamento do Tesouro dos Estados Unidos o listar como um cidadão especialmente designado e/ou pessoa bloqueada; (2) a Secretaria da Indústria e Segurança do Ministério do Comércio dos Estados Unidos o incluir em sua lista de pessoas impedidas ou em listas de suspeitos; ou (3) você estiver em uma lista semelhante promulgada por uma agência ou departamento oficial do governo dos Estados Unidos. Você garante e declara que não está localizado em algum país embargado, ou sob o controle desse país, nem é seu cidadão ou residente.</p>
<h4>20.10. <u>Se parte desses Termos for invalidada, o que acontece com o restante?</u> (Como Zac, esses Termos podem perder uma parte ou duas, mas o que restar permanecerá vivo.)</h4>
<p>Salvo disposição em contrário nestes Termos, se qualquer disposição destes Termos for considerada inválida ou inexequível por qualquer motivo, tal disposição será considerada separada destes Termos e as demais disposições continuarão em pleno vigor.</p>
<h4>20.11. <u>Esses títulos engraçados são juridicamente vinculativos?</u> (Não. Esses títulos são apenas a maneira de nossos advogados tentarem ser cativantes e divertidos. Outros advogados acham que esses títulos são mesmo cativantes e divertidos.)</h4>
<p>Os títulos e trechos entre parênteses nestes Termos são fornecidos apenas para fins informativos e de entretenimento. Eles não têm nenhum efeito jurídico.</p>
<h4>20.12. Quanto tempo dura este contrato? (Enquanto você usar os Serviços da ADS Store ou até que sua conta seja encerrada. Porém, algumas disposições foram “ressuscitadas” no Chronoshift e duram para sempre.)</h4>
<p>Estes Termos começam na data em que você os aceitar pela primeira vez e permanecerão válidos enquanto você utilizar ou mantiver uma conta nos Serviços da ADS Store. Contudo, as Cláusulas <a href="#id.v30qlwhh3j79">2.3</a>, <a href="#id.xyyxssr12ehd">3.2</a>, <a href="#id.lrs9z6amtdb4">4.3</a>, <a href="#id.z04985mbb9pr">4.4</a>, <a href="#id.gc8zdnrizurg">4.5</a>, <a href="#id.a53inplgg9a">5.1</a>, <a href="#id.29jn1srhli8v">6</a>, <a href="#id.a1s6fxqza1tl">8</a>, e <a href="#id.d0rk78307ojs">13-19</a> inclusive, sobreviverão ao término destes Termos.</p>
<h4>20.13. <u>Quando dizemos "inclusive" nestes Termos, significa uma limitação?</u> (Não.)</h4>
<p>Sempre que usamos o termo "inclusive" nestes Termos, queremos dizer "inclusive, sem limitação"</p>
<p><strong>VOCÊ DESDE JÁ RECONHECE E CONCORDA QUE LEU E COMPREENDEU ESTES TERMOS, E QUE, AO CLICAR NO BOTÃO "ACEITAR" ABAIXO OU DE OUTRA MANEIRA UTILIZAR OU ACESSAR OS SERVIÇOS DA ADS Store, VOCÊ ESTARÁ CONCORDANDO EM OBRIGAR-SE AOS TERMOS E ÀS CONDIÇÕES PREVISTAS NESTES TERMOS.</strong></p>
<br/>
        </div>
        </>
    )
}